### ISSUE TITLE
Github 'About' says 'Java' not 'JavaScript'

### ISSUE THREAD

**Issue by grempe** [Lepozepo/qldb#10]
The Github `About` for this repo (top right of page) says:

```
About
QLDB driver for node using the Java driver
```

It should say `QLDB driver for Node.js using the JavaScript driver.`

**Comment by Lepozepo** [comment]
Hi @grempe ! The first version of this used the original Java Driver but has been upgraded since, good call!

**Comment by Lepozepo** [comment]
Updated :D
